config/routes.rb
MeetUp::Application.routes.draw do


  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy', as: 'session'



  resources :join_groups


  resources :groups


  resources :join_meets


  resources :meets


  resources :cities


  resources :states


  resources :users

  root to: 'meets#index'

end

app/models/join_group.rb
class JoinGroup < ActiveRecord::Base
  attr_accessible :group_id, :user_id
  belongs_to :group
  belongs_to :user

  validates :group, presence: true
  validates :user, presence: true
  validates :user_id, uniqueness: { scope: :group_id }
  after_create :increase_user_count
  after_destroy :decrease_user_count
  def getID(group_id, user_id)
    return JoinGroup.where(:group_id=>group_id, :user_id=>user_id).id
  end
  private
    def increase_user_count
      group = self.group
      group.user_count += 1
      group.save
    end
    def decrease_user_count
      group = self.group
      group.user_count -= 1
      group.save
    end
end

app/controllers/join_groups_controller.rb
class JoinGroupsController < ApplicationController
  before_filter :authorize_user, only: [:edit, :update, :destroy]

  def authorize_user
    join_group = JoinGroup.find(params[:id])

    if join_group.user != current_user
      redirect_to meets_url, notice: "Nice try, Jeff."
    end
  end
  # GET /join_groups
  # GET /join_groups.json
  def index
    @join_groups = JoinGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @join_groups }
    end
  end

  # GET /join_groups/1
  # GET /join_groups/1.json
  def show
    @join_group = JoinGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @join_group }
    end
  end

  # GET /join_groups/new
  # GET /join_groups/new.json
  def new
    @join_group = JoinGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @join_group }
    end
  end

  # GET /join_groups/1/edit
  def edit
    @join_group = JoinGroup.find(params[:id])
  end

  # POST /join_groups
  # POST /join_groups.json
  def create
    @join_group = JoinGroup.new(params[:join_group])
    @join_group.user_id = session[:user_id]

    respond_to do |format|
      if @join_group.save
        format.html { redirect_to @join_group, notice: 'Join group was successfully created.' }
        format.json { render json: @join_group, status: :created, location: @join_group }
      else
        format.html { render action: "new" }
        format.json { render json: @join_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /join_groups/1
  # PUT /join_groups/1.json
  def update
    @join_group = JoinGroup.find(params[:id])

    respond_to do |format|
      if @join_group.update_attributes(params[:join_group])
        format.html { redirect_to @join_group, notice: 'Join group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @join_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /join_groups/1
  # DELETE /join_groups/1.json
  def destroy
    @join_group = JoinGroup.find(params[:id])
    @join_group.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to join_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/join_groups_helper.rb
module JoinGroupsHelper
end

app/views/join_groups/_form.html.erb
<%= form_for(@join_group) do |f| %>
  <% if @join_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@join_group.errors.count, "error") %> prohibited this join_group from being saved:</h2>

      <ul>
      <% @join_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.collection_select :group_id, Group.all, :id, :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/join_groups/destroy.js.erb
if(user_page){
  $("#group_<%=@join_group.group_id%>").hide();
}

app/views/join_groups/edit.html.erb
<h1>Editing join_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @join_group %> |
<%= link_to 'Back', join_groups_path %>

app/views/join_groups/index.html.erb
<h1>Listing join_groups</h1>

<table>
  <tr>
    <th>Group</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @join_groups.each do |join_group| %>
  <tr>
    <td><%= join_group.group.title %></td>
    <td><%= join_group.user.name %></td>
    <td><%= link_to 'Show', join_group %></td>
    <td><%= link_to 'Edit', edit_join_group_path(join_group) %></td>
    <td><%= link_to 'Destroy', join_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Join group', new_join_group_path %>

app/views/join_groups/new.html.erb
<h1>New join_group</h1>

<%= render 'form' %>

<%= link_to 'Back', join_groups_path %>

app/views/join_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @join_group.group.title %>
</p>

<p>
  <b>User:</b>
  <%= @join_group.user.name %>
</p>


<%= link_to 'Edit', edit_join_group_path(@join_group) %> |
<%= link_to 'Back', join_groups_path %>