config/routes.rb
MeetUp::Application.routes.draw do


  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy', as: 'session'



  resources :join_groups


  resources :groups


  resources :join_meets


  resources :meets


  resources :cities


  resources :states


  resources :users

  root to: 'meets#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :introduction, :name, :password, :password_confirmation, :state
  has_secure_password
  validates_uniqueness_of :name, :email
  has_many :group
  has_many :join_group
  has_many :meet
  has_many :join_meet
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @meets = Meet.paginate(:page => params[:page], :per_page => 5).joins(:join_meet).where("join_meets.user_id"=>current_user.id)
    @groups = Group.paginate(:page => params[:page], :per_page => 5).joins(:join_group).where("join_groups.user_id"=>current_user.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.state = false

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :introduction %><br />
    <%= f.text_field :introduction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>ß
    <th>Email</th>
    <th>Introduction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.introduction %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Introduction:</b>
  <%= @user.introduction %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<h1 id="meet">The meets you have joined.</h1>
<%= will_paginate @meets %>
<table id="meet_table">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Starter</th>
    <th>City</th>
    <th>Date</th>
    <th>Count</th>
    <%if signed_in?%>
      <th></th>
    <%end%>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meets.each do |meet| %>
  <tr id="meet_<%=meet.id%>">
    <td><%= meet.title %></td>
    <td><%= meet.content %></td>
    <td><%= meet.user.name %></td>
    <td><%= meet.city.full_name %></td>
    <td><%= meet.date %></td>
    <td><%= meet.user_count %></td>
    <%if signed_in?%>
      <% if current_user.join_meet.where(:meet_id => meet.id).count == 0%>
        <td><%= link_to 'Join', {:controller => "join_meets",
          :action => "create", :join_meet=>{:meet_id=>meet.id}}, method: :post%></td>
      <%else%>
        <td><%= link_to 'Disjoin', {:controller => "join_meets",
          :action => "destroy", :id=>getJoinMeetID(meet.id, current_user.id)}, method: :delete, data: { confirm: 'Are you sure?' }, remote: true%></td>
      <% end%>
    <%end%>
    <td><%= link_to 'Show', meet %></td>
    <%if meet.user == current_user%>
      <td><%= link_to 'Edit', edit_meet_path(meet) %></td>
      <td><%= link_to 'Destroy', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

<hr>
<h1 id="group">The groups you have joined.</h1>
<%= will_paginate @groups %>
<table id="group_table">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Starter</th>
    <th>Count</th>
    <%if signed_in?%>
      <th></th>
    <%end%>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr id="group_<%=group.id%>">
    <td><%= group.title %></td>
    <td><%= group.description %></td>
    <td><%= group.user.name %></td>
    <td><%= group.user_count %></td>
    <%if signed_in?%>
      <% if current_user.join_group.where(:group_id => group.id).count == 0%>
        <td><%= link_to 'Join', {:controller => "join_groups",
          :action => "create", :join_group=>{:group_id=>group.id}}, method: :post%></td>
      <%else%>
        <td><%= link_to 'Disjoin', {:controller => "join_groups",
          :action => "destroy", :id=>getJoinGroupID(group.id, current_user.id)}, method: 'delete', remote: true, data: { confirm: 'Are you sure?' }%></td>
      <% end%>
    <%end%>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<script type="text/javascript">
$("#meet").on("click", function(){
  $("#meet_table").slideToggle();
});
$("#group").on("click", function(){
  $("#group_table").slideToggle();
});
var user_page = true;
</script>