config/routes.rb
MeetUp::Application.routes.draw do


  get '/sessions/new' => 'Sessions#new', as: 'new_session'
  post '/sessions' => 'Sessions#create', as: 'sessions'
  delete '/sessions' => 'Sessions#destroy', as: 'session'



  resources :join_groups


  resources :groups


  resources :join_meets


  resources :meets


  resources :cities


  resources :states


  resources :users

  root to: 'meets#index'

end

app/models/meet.rb
class Meet < ActiveRecord::Base
  attr_accessible :city_id, :content, :title, :user_id, :user_count, :date
  belongs_to :city
  belongs_to :user
  has_many :join_meet
  validates_uniqueness_of :title, :date
  after_create :join_this_meet
  private
    def join_this_meet
      join_meet = JoinMeet.new
      join_meet.meet_id = self.id
      join_meet.user_id = self.user_id
      join_meet.save
    end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_filter :authorize_user, only: [:edit, :update, :destroy]

  def authorize_user
    meet = Meet.find(params[:id])

    if meet.user != current_user
      redirect_to meets_url, notice: "Nice try, Jeff."
    end
  end
  # GET /meets
  # GET /meets.json
  def index
    @meets = Meet.paginate(:page => params[:page], :per_page => 5).order("date desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meets }
    end
  end

  # GET /meets/1
  # GET /meets/1.json
  def show
    @meet = Meet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meet }
    end
  end

  # GET /meets/new
  # GET /meets/new.json
  def new
    @meet = Meet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meet }
    end
  end

  # GET /meets/1/edit
  def edit
    @meet = Meet.find(params[:id])
  end

  # POST /meets
  # POST /meets.json
  def create
    @meet = Meet.new(params[:meet])
    @meet.user_id = session[:user_id]
    @meet.user_count = 0

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: 'Meet was successfully created.' }
        format.json { render json: @meet, status: :created, location: @meet }
      else
        format.html { render action: "new" }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meets/1
  # PUT /meets/1.json
  def update
    @meet = Meet.find(params[:id])

    respond_to do |format|
      if @meet.update_attributes(params[:meet])
        format.html { redirect_to @meet, notice: 'Meet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1
  # DELETE /meets/1.json
  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy

    respond_to do |format|

      format.html { redirect_to meets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/views/meets/_form.html.erb
<%= form_for(@meet) do |f| %>
  <% if @meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
      <% @meet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br />
    <%= f.collection_select :city_id, City.all, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meets/_index_table.html.erb
<%= will_paginate @meets %>
<table id="meet_table">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Starter</th>
    <th>City</th>
    <th>Date</th>
    <th>Count</th>
    <%if signed_in?%>
      <th></th>
    <%end%>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meets.each do |meet| %>
  <tr id="meet_<%=meet.id%>">
    <td><%= meet.title %></td>
    <td><%= meet.content %></td>
    <td><%= meet.user.name %></td>
    <td><%= meet.city.full_name %></td>
    <td><%= meet.date %></td>
    <td><%= meet.user_count %></td>
    <%if signed_in?%>
      <% if current_user.join_meet.where(:meet_id => meet.id).count == 0%>
        <td><%= link_to 'Join', {:controller => "join_meets",
          :action => "create", :join_meet=>{:meet_id=>meet.id}}, method: :post%></td>
      <%else%>
        <td><%= link_to 'Disjoin', {:controller => "join_meets",
          :action => "destroy", :id=>getJoinMeetID(meet.id, current_user.id)}, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      <% end%>
    <%end%>
    <td><%= link_to 'Show', meet %></td>
    <%if meet.user == current_user%>
      <td><%= link_to 'Edit', edit_meet_path(meet) %></td>
      <td><%= link_to 'Destroy', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

app/views/meets/edit.html.erb
<h1>Editing meet</h1>

<%= render 'form' %>

<%= link_to 'Show', @meet %> |
<%= link_to 'Back', meets_path %>

app/views/meets/index.html.erb
<h1>Listing meets</h1>
<%= will_paginate @meets %>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Starter</th>
    <th>City</th>
    <th>Date</th>
    <th>Count</th>
    <%if signed_in?%>
      <th></th>
    <%end%>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meets.each do |meet| %>
  <tr>
    <td><%= meet.title %></td>
    <td><%= meet.content %></td>
    <td><%= meet.user.name %></td>
    <td><%= meet.city.full_name %></td>
    <td><%= meet.date %></td>
    <td><%= meet.user_count %></td>
    <%if signed_in?%>
      <% if current_user.join_meet.count(meet.id) == 0%>
        <td><%= link_to 'Join', {:controller => "join_meets",
          :action => "create", :join_meet=>{:meet_id=>meet.id}}, method: :post%></td>
      <%else%>
        <td><%= link_to 'Disjoin', {:controller => "join_meets",
          :action => "destroy", :id=>getJoinMeetID(meet.id, current_user.id)}, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      <% end%>
    <%end%>
    <td><%= link_to 'Show', meet %></td>
    <td><%= link_to 'Edit', edit_meet_path(meet) %></td>
    <td><%= link_to 'Destroy', meet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meet', new_meet_path %>

app/views/meets/new.html.erb
<h1>New meet</h1>

<%= render 'form' %>

<%= link_to 'Back', meets_path %>

app/views/meets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @meet.title %>
</p>

<p>
  <b>Content:</b>
  <%= @meet.content %>
</p>

<p>
  <b>Starter:</b>
  <%= @meet.user.name %>
</p>

<p>
  <b>City:</b>
  <%= @meet.city.full_name %>
</p>

<p>
  <b>Date:</b>
  <%= @meet.date %>
</p>

<p>
  <b>Count:</b>
  <%= @meet.user_count %>
</p>

<%if signed_in?%>
  <% if current_user.join_meet.count(@meet.id) == 0%>
    <td><%= link_to 'Join', {:controller => "join_meets",
      :action => "create", :join_meet=>{:meet_id=>@meet.id}}, method: :post%></td>
  <%else%>
    <td><%= link_to 'Disjoin', {:controller => "join_meets",
      :action => "destroy", :id=>getJoinMeetID(@meet.id, current_user.id)}, method: :delete, data: { confirm: 'Are you sure?' }%></td>
  <% end%>
<%end%>
<%= link_to 'Edit', edit_meet_path(@meet) %> |
<%= link_to 'Back', meets_path %>